import dotenv from 'dotenv';
dotenv.config();

const DEFAULT_STORE_ID = '141633269';
// Official public token for EarthLife Co. read-only catalog access
const DEFAULT_PUBLIC_TOKEN = 'public_19bKp94DXNgXAenj9iRmy7FicBjUMQHH';

export function getEcwidConfig() {
  const storeId = process.env.ECWID_STORE_ID || process.env.VITE_ECWID_STORE_ID || DEFAULT_STORE_ID;
  const token = process.env.ECWID_SECRET_TOKEN || process.env.ECWID_PUBLIC_TOKEN || DEFAULT_PUBLIC_TOKEN;
  return { storeId, token };
}

/**
 * Normalizes an Ecwid API product object into the shape expected by EarthLife Co. UI
 */
export function normalizeProduct(raw, categories = []) {
  if (!raw) return null;

  const id = raw.id;
  const ecwidId = String(raw.id);
  const slug = raw.autogeneratedSlug || raw.customSlug || String(raw.id);
  const name = raw.name || '';
  const sku = raw.sku || '';
  const price = typeof raw.price === 'number' ? raw.price : Number(raw.price || 0);
  const compareToPrice = typeof raw.compareToPrice === 'number' && raw.compareToPrice > price 
    ? raw.compareToPrice 
    : null;
  const discountPercent = raw.compareToPriceDiscountPercent 
    || (compareToPrice ? Math.round((1 - price / compareToPrice) * 100) : null);

  // Highest resolution main image
  const image = raw.imageUrl 
    || raw.originalImageUrl 
    || raw.hdThumbnailUrl 
    || raw.thumbnailUrl 
    || raw.media?.images?.[0]?.image1500pxUrl 
    || '';

  // Clean deduplicated gallery images
  const gallery = [];
  if (image) gallery.push(image);
  
  if (Array.isArray(raw.galleryImages)) {
    raw.galleryImages.forEach(g => {
      const u = g.imageUrl || g.originalImageUrl || g.url || g.hdThumbnailUrl;
      if (u && !gallery.includes(u)) gallery.push(u);
    });
  }
  if (Array.isArray(raw.media?.images)) {
    raw.media.images.forEach(img => {
      const u = img.image1500pxUrl || img.image800pxUrl || img.imageOriginalUrl;
      if (u && !gallery.includes(u)) gallery.push(u);
    });
  }
  if (gallery.length === 0 && image) gallery.push(image);

  // Category resolution
  const categoryIds = Array.isArray(raw.categoryIds) ? raw.categoryIds : [];
  const defaultCategoryId = raw.defaultCategoryId || (categoryIds[0] ?? 0);
  
  // Resolve category name and type based on Ecwid category tree or product name
  let categoryName = 'General';
  let categoryType = 'all';
  let categoryTag = 'Natural';

  const categoryIdNum = Number(defaultCategoryId || categoryIds[0] || 0);

  if (categoryIdNum === 206710677 || name.toLowerCase().includes('neem')) {
    categoryName = 'Neem Products';
    categoryType = 'neem';
    categoryTag = 'Neem Wood';
  } else if (categoryIdNum === 206706898 || name.toLowerCase().includes('bamboo')) {
    categoryName = 'Bamboo Products';
    categoryType = 'bamboo';
    categoryTag = 'Bamboo';
  } else if (categoryIdNum === 206708145 || name.toLowerCase().includes('coconut') || name.toLowerCase().includes('coir')) {
    categoryName = 'Coconut Coir Products';
    categoryType = 'coconut';
    categoryTag = 'Coconut Coir';
  } else if (categories.length > 0) {
    const matched = categories.find(c => c.id === categoryIdNum);
    if (matched) {
      categoryName = matched.name;
      categoryTag = matched.name;
    }
  }

  return {
    id,
    ecwidId,
    slug,
    name,
    sku,
    price,
    compareToPrice,
    discountPercent,
    image,
    gallery,
    description: raw.description || '',
    inStock: Boolean(raw.inStock),
    unlimited: Boolean(raw.unlimited),
    quantity: typeof raw.quantity === 'number' ? raw.quantity : null,
    weight: typeof raw.weight === 'number' && raw.weight > 0 ? raw.weight : null,
    categoryName,
    categoryType,
    categoryTag,
    categoryId: categoryIdNum ? String(categoryIdNum) : '',
    categoryIds,
    defaultCategoryId,
    options: Array.isArray(raw.options) ? raw.options : [],
    attributes: Array.isArray(raw.attributes) ? raw.attributes : [],
    combinations: Array.isArray(raw.combinations) ? raw.combinations : [],
    url: raw.url || '',
    showOnFrontpage: typeof raw.showOnFrontpage === 'number' ? raw.showOnFrontpage : null,
    ribbon: raw.ribbon || null,
    subtitle: raw.subtitle || ''
  };
}

async function fetchWithRetry(url, options = {}, retries = 2) {
  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 8000);
      const res = await fetch(url, { ...options, signal: controller.signal });
      clearTimeout(timeoutId);
      return res;
    } catch (err) {
      if (attempt === retries) throw err;
      await new Promise(r => setTimeout(r, 300 * (attempt + 1)));
    }
  }
}

const ECWID_CATEGORY_MAP = {
  neem: '206710677',
  'neem-products': '206710677',
  bamboo: '206706898',
  'bamboo-products': '206706898',
  coconut: '206708145',
  'coconut-coir': '206708145',
  'cotton-coir': '206708145',
  'coir': '206708145',
  'cotton': '206708145',
  'coconut-coir-products': '206708145',
};

function resolveCategoryId(cat) {
  if (!cat || cat === '0' || cat === 'all') return null;
  const normalized = String(cat).trim().toLowerCase();
  if (ECWID_CATEGORY_MAP[normalized]) return ECWID_CATEGORY_MAP[normalized];
  if (/^\d+$/.test(normalized)) return normalized;
  return null;
}

/**
 * Handles incoming Ecwid API proxy requests
 */
export async function handleEcwidApi(req, res) {
  const urlObj = new URL(req.url, 'http://localhost');
  const pathname = urlObj.pathname;
  const cleanPath = pathname.replace(/\/+$/, '') || '/';
  const { storeId, token } = getEcwidConfig();

  // Set permissive CORS and JSON headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, HEAD, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Accept, Authorization');
  res.setHeader('Content-Type', 'application/json');

  if (req.method === 'OPTIONS') {
    res.statusCode = 204;
    return res.end();
  }

  const isGetOrHead = req.method === 'GET' || req.method === 'HEAD';
  const isPost = req.method === 'POST';

  try {
    // 1. GET /api/ecwid/products
    if (cleanPath === '/api/ecwid/products' && isGetOrHead) {
      const keyword = urlObj.searchParams.get('keyword');
      const category = urlObj.searchParams.get('category');
      const limit = urlObj.searchParams.get('limit') || '100';
      const offset = urlObj.searchParams.get('offset') || '0';

      const ecwidUrl = new URL(`https://app.ecwid.com/api/v3/${storeId}/products`);
      ecwidUrl.searchParams.set('token', token);
      ecwidUrl.searchParams.set('limit', limit);
      ecwidUrl.searchParams.set('offset', offset);
      if (keyword) ecwidUrl.searchParams.set('keyword', keyword);
      const resolvedCategory = resolveCategoryId(category);
      if (resolvedCategory) {
        ecwidUrl.searchParams.set('category', resolvedCategory);
      }

      const response = await fetchWithRetry(ecwidUrl.toString(), {
        headers: { 'Accept': 'application/json' }
      });

      if (!response.ok) {
        const errorText = await response.text();
        res.statusCode = response.status;
        return res.end(JSON.stringify({ 
          error: `Ecwid API error: ${response.statusText}`, 
          details: errorText 
        }));
      }

      const data = await response.json();
      const normalizedItems = (data.items || []).map(p => normalizeProduct(p));

      res.statusCode = 200;
      return res.end(JSON.stringify({
        storeId,
        source: 'ecwid_live_api',
        total: data.total,
        count: data.count,
        offset: data.offset,
        limit: data.limit,
        items: normalizedItems,
        rawItems: data.items
      }));
    }

    // 2. GET /api/ecwid/products/:id
    if (cleanPath.startsWith('/api/ecwid/products/') && isGetOrHead) {
      const idOrSlug = decodeURIComponent(cleanPath.replace('/api/ecwid/products/', '')).trim();

      if (!idOrSlug) {
        res.statusCode = 400;
        return res.end(JSON.stringify({ error: 'Product ID or slug is required.' }));
      }

      const isNumeric = /^\d+$/.test(idOrSlug);

      if (isNumeric) {
        // Direct fetch by numeric ID
        const singleUrl = `https://app.ecwid.com/api/v3/${storeId}/products/${idOrSlug}?token=${token}`;
        const singleRes = await fetchWithRetry(singleUrl, {
          headers: { 'Accept': 'application/json' }
        });

        if (singleRes.ok) {
          const raw = await singleRes.json();
          res.statusCode = 200;
          return res.end(JSON.stringify({
            storeId,
            source: 'ecwid_live_api',
            product: normalizeProduct(raw),
            raw
          }));
        }
      }

      // If not numeric or direct fetch failed, search products to match by slug or SKU
      const searchUrl = `https://app.ecwid.com/api/v3/${storeId}/products?token=${token}&limit=100`;
      const searchRes = await fetchWithRetry(searchUrl, {
        headers: { 'Accept': 'application/json' }
      });

      if (!searchRes.ok) {
        res.statusCode = 404;
        return res.end(JSON.stringify({ error: 'Product not found.' }));
      }

      const listData = await searchRes.json();
      const match = (listData.items || []).find(p => 
        String(p.id) === idOrSlug ||
        p.autogeneratedSlug === idOrSlug ||
        p.customSlug === idOrSlug ||
        (p.sku && p.sku.toLowerCase() === idOrSlug.toLowerCase()) ||
        idOrSlug.includes(p.autogeneratedSlug) ||
        (p.autogeneratedSlug && p.autogeneratedSlug.includes(idOrSlug))
      );

      if (!match) {
        res.statusCode = 404;
        return res.end(JSON.stringify({ error: 'Product not found.' }));
      }

      // Fetch full individual product for complete gallery and options
      const fullRes = await fetchWithRetry(`https://app.ecwid.com/api/v3/${storeId}/products/${match.id}?token=${token}`, {
        headers: { 'Accept': 'application/json' }
      });

      const raw = fullRes.ok ? await fullRes.json() : match;
      res.statusCode = 200;
      return res.end(JSON.stringify({
        storeId,
        source: 'ecwid_live_api',
        product: normalizeProduct(raw),
        raw
      }));
    }

    // 3. GET /api/ecwid/categories
    if (cleanPath === '/api/ecwid/categories' && isGetOrHead) {
      const catUrl = `https://app.ecwid.com/api/v3/${storeId}/categories?token=${token}`;
      const catRes = await fetchWithRetry(catUrl, {
        headers: { 'Accept': 'application/json' }
      });

      if (!catRes.ok) {
        const errText = await catRes.text();
        res.statusCode = catRes.status;
        return res.end(JSON.stringify({ error: 'Failed to fetch categories', details: errText }));
      }

      const data = await catRes.json();
      res.statusCode = 200;
      return res.end(JSON.stringify({
        storeId,
        source: 'ecwid_live_api',
        total: data.total,
        items: data.items || []
      }));
    }

    // 4. POST /api/ecwid/cart/calculate (Authoritative Ecwid Cart Calculation)
    if (cleanPath === '/api/ecwid/cart/calculate' && (isPost || isGetOrHead)) {
      let bodyData = {};
      if (isPost) {
        if (req.body && typeof req.body === 'object') {
          bodyData = req.body;
        } else {
          bodyData = await new Promise((resolve) => {
            let buffer = '';
            req.on('data', chunk => { buffer += chunk; });
            req.on('end', () => {
              try {
                resolve(buffer ? JSON.parse(buffer) : {});
              } catch {
                resolve({});
              }
            });
            req.on('error', () => resolve({}));
          });
        }
      } else {
        const itemsParam = urlObj.searchParams.get('items');
        if (itemsParam) {
          try {
            bodyData = { items: JSON.parse(decodeURIComponent(itemsParam)) };
          } catch {
            bodyData = { items: [] };
          }
        }
      }

      const inputItems = Array.isArray(bodyData.items) ? bodyData.items : [];
      const couponCode = bodyData.couponCode ? String(bodyData.couponCode).trim() : null;

      if (inputItems.length === 0) {
        res.statusCode = 200;
        return res.end(JSON.stringify({
          storeId,
          source: 'ecwid_live_api',
          subtotal: 0,
          subtotalWithoutTax: 0,
          total: 0,
          totalWithoutTax: 0,
          tax: 0,
          taxes: [],
          shipping: 0,
          discount: 0,
          couponDiscount: 0,
          volumeDiscount: 0,
          items: []
        }));
      }

      // Format items adhering to Ecwid OrderItem and OrderItemProductOption specs
      const ecwidCalcPayload = {
        items: inputItems.map(item => {
          const selectedOptions = [];
          if (Array.isArray(item.selectedOptions)) {
            item.selectedOptions.forEach(opt => {
              if (opt && opt.name) {
                selectedOptions.push({
                  name: String(opt.name),
                  value: String(opt.value || ''),
                  type: String(opt.type || 'CHOICE')
                });
              }
            });
          } else if (item.options && typeof item.options === 'object') {
            Object.entries(item.options).forEach(([optName, optVal]) => {
              if (optVal !== undefined && optVal !== null) {
                selectedOptions.push({
                  name: String(optName),
                  value: String(optVal),
                  type: 'CHOICE'
                });
              }
            });
          }

          return {
            productId: Number(item.productId || item.id),
            name: item.name || '',
            price: Number(item.price || 0),
            quantity: Math.max(1, Number(item.quantity || 1)),
            sku: item.sku || '',
            selectedOptions: selectedOptions.length > 0 ? selectedOptions : undefined
          };
        })
      };

      if (bodyData.shippingAddress && typeof bodyData.shippingAddress === 'object') {
        const addr = bodyData.shippingAddress;
        ecwidCalcPayload.shippingAddress = {
          name: addr.name || addr.fullName || '',
          companyName: addr.companyName || '',
          street: addr.street || addr.address1 || '',
          city: addr.city || '',
          countryCode: addr.countryCode || 'IN',
          postalCode: addr.postalCode || addr.pincode || addr.pinCode || '',
          stateOrProvinceCode: addr.stateOrProvinceCode || addr.state || '',
          phone: addr.phone || ''
        };
      }

      if (bodyData.customer && typeof bodyData.customer === 'object') {
        ecwidCalcPayload.customer = {
          email: bodyData.customer.email || '',
          name: bodyData.customer.name || ''
        };
      }

      if (couponCode) {
        ecwidCalcPayload.couponCode = couponCode;
      }

      const calcUrl = `https://app.ecwid.com/api/v3/${storeId}/order/calculate?token=${token}`;
      const calcRes = await fetchWithRetry(calcUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify(ecwidCalcPayload)
      });

      if (calcRes.ok) {
        let calcData = null;
        try {
          const text = await calcRes.text();
          if (text && text.trim() && text.trim() !== 'undefined') {
            calcData = JSON.parse(text);
          }
        } catch (e) {
          console.error('Failed to parse Ecwid order calculate response:', e);
        }

        if (calcData) {
          res.statusCode = 200;
          return res.end(JSON.stringify({
            storeId,
            source: 'ecwid_live_api',
            subtotal: typeof calcData.subtotal === 'number' ? calcData.subtotal : 0,
            subtotalWithoutTax: typeof calcData.subtotalWithoutTax === 'number' ? calcData.subtotalWithoutTax : 0,
            total: typeof calcData.total === 'number' ? calcData.total : 0,
            totalWithoutTax: typeof calcData.totalWithoutTax === 'number' ? calcData.totalWithoutTax : 0,
            tax: typeof calcData.tax === 'number' ? calcData.tax : 0,
            taxes: Array.isArray(calcData.taxes) ? calcData.taxes : [],
            shipping: typeof calcData.shipping === 'number' ? calcData.shipping : 0,
            discount: typeof calcData.discount === 'number' ? calcData.discount : 0,
            couponDiscount: typeof calcData.couponDiscount === 'number' ? calcData.couponDiscount : 0,
            volumeDiscount: typeof calcData.volumeDiscount === 'number' ? calcData.volumeDiscount : 0,
            items: Array.isArray(calcData.items) ? calcData.items : [],
            raw: calcData
          }));
        }
      }

      // Fallback: If Ecwid order/calculate rejects an invalid coupon or param, retry without coupon
      if (couponCode) {
        delete ecwidCalcPayload.couponCode;
        const retryRes = await fetchWithRetry(calcUrl, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Accept': 'application/json' },
          body: JSON.stringify(ecwidCalcPayload)
        });
        if (retryRes.ok) {
          let calcData = null;
          try {
            const text = await retryRes.text();
            if (text && text.trim() && text.trim() !== 'undefined') {
              calcData = JSON.parse(text);
            }
          } catch (e) {
            console.error('Failed to parse Ecwid retry calculate response:', e);
          }

          if (calcData) {
            res.statusCode = 200;
            return res.end(JSON.stringify({
              storeId,
              source: 'ecwid_live_api',
              subtotal: typeof calcData.subtotal === 'number' ? calcData.subtotal : 0,
              subtotalWithoutTax: typeof calcData.subtotalWithoutTax === 'number' ? calcData.subtotalWithoutTax : 0,
              total: typeof calcData.total === 'number' ? calcData.total : 0,
              totalWithoutTax: typeof calcData.totalWithoutTax === 'number' ? calcData.totalWithoutTax : 0,
              tax: typeof calcData.tax === 'number' ? calcData.tax : 0,
              taxes: Array.isArray(calcData.taxes) ? calcData.taxes : [],
              shipping: typeof calcData.shipping === 'number' ? calcData.shipping : 0,
              discount: 0,
              couponDiscount: 0,
              volumeDiscount: 0,
              couponError: 'Invalid coupon code',
              items: Array.isArray(calcData.items) ? calcData.items : [],
              raw: calcData
            }));
          }
        }
      }

      // If calculate still fails, calculate deterministic subtotal from prices
      const simpleSubtotal = inputItems.reduce((acc, it) => acc + (Number(it.price || 0) * Math.max(1, Number(it.quantity || 1))), 0);
      res.statusCode = 200;
      return res.end(JSON.stringify({
        storeId,
        source: 'ecwid_local_fallback',
        subtotal: simpleSubtotal,
        subtotalWithoutTax: simpleSubtotal,
        total: simpleSubtotal,
        totalWithoutTax: simpleSubtotal,
        tax: 0,
        taxes: [],
        shipping: 0,
        discount: 0,
        couponDiscount: 0,
        volumeDiscount: 0,
        items: inputItems
      }));
    }

    // 5. GET /api/ecwid/customer/addresses - Check if customer address storage is supported via Ecwid Secret Token
    if (cleanPath === '/api/ecwid/customer/addresses' && isGetOrHead) {
      const email = urlObj.searchParams.get('email');
      const hasSecretToken = Boolean(process.env.ECWID_SECRET_TOKEN);

      if (!hasSecretToken) {
        res.statusCode = 200;
        return res.end(JSON.stringify({
          supported: false,
          requiresSecretToken: true,
          message: 'Ecwid Secret Token (ECWID_SECRET_TOKEN) with read_customers/update_customers scope is required to query or persist customer addresses directly to the remote Ecwid Customer database. Using customer checkout session storage.',
          addresses: []
        }));
      }

      // If secret token is present, query Ecwid customers API
      try {
        const customerUrl = new URL(`https://app.ecwid.com/api/v3/${storeId}/customers`);
        customerUrl.searchParams.set('token', token);
        if (email) customerUrl.searchParams.set('email', email);

        const customerRes = await fetchWithRetry(customerUrl.toString(), {
          headers: { 'Accept': 'application/json' }
        });

        if (!customerRes.ok) {
          res.statusCode = 200;
          return res.end(JSON.stringify({
            supported: false,
            error: customerRes.statusText,
            addresses: []
          }));
        }

        const customerData = await customerRes.json();
        const customer = (customerData.items || [])[0];
        const addresses = [];

        if (customer) {
          if (customer.shippingAddresses && Array.isArray(customer.shippingAddresses)) {
            addresses.push(...customer.shippingAddresses);
          } else if (customer.billingAddress) {
            addresses.push(customer.billingAddress);
          }
        }

        res.statusCode = 200;
        return res.end(JSON.stringify({
          supported: true,
          addresses
        }));
      } catch (err) {
        res.statusCode = 200;
        return res.end(JSON.stringify({
          supported: false,
          error: err.message,
          addresses: []
        }));
      }
    }

    // 5b. POST /api/ecwid/customer/update - Real Ecwid Customer Profile Update
    if (cleanPath === '/api/ecwid/customer/update' && isPost) {
      let bodyData = {};
      if (req.body && typeof req.body === 'object') {
        bodyData = req.body;
      } else {
        bodyData = await new Promise((resolve) => {
          let buffer = '';
          req.on('data', chunk => { buffer += chunk; });
          req.on('end', () => {
            try {
              resolve(buffer ? JSON.parse(buffer) : {});
            } catch {
              resolve({});
            }
          });
          req.on('error', () => resolve({}));
        });
      }

      const { customerId, email, name, phone, acceptsMarketing } = bodyData;
      const hasSecretToken = Boolean(process.env.ECWID_SECRET_TOKEN);

      if (!hasSecretToken) {
        res.statusCode = 200;
        return res.end(JSON.stringify({
          success: false,
          requiresStorefrontAction: true,
          message: 'Direct REST API customer updates require an Ecwid Secret Token (ECWID_SECRET_TOKEN) with update_customers scope. Please use the official Ecwid Account Settings to update and save your profile.'
        }));
      }

      try {
        let targetId = customerId;
        if (!targetId && email) {
          // Look up customer ID by email
          const searchUrl = `https://app.ecwid.com/api/v3/${storeId}/customers?token=${token}&email=${encodeURIComponent(email)}`;
          const searchRes = await fetchWithRetry(searchUrl, {
            headers: { 'Accept': 'application/json' }
          });
          if (searchRes.ok) {
            const data = await searchRes.json();
            if (data.items && data.items.length > 0) {
              targetId = data.items[0].id;
            }
          }
        }

        if (!targetId) {
          res.statusCode = 400;
          return res.end(JSON.stringify({
            success: false,
            message: 'Customer ID or valid customer email is required.'
          }));
        }

        const updatePayload = {};
        if (name !== undefined) {
          updatePayload.name = name;
          updatePayload.billingPerson = { name };
        }
        if (phone !== undefined) {
          updatePayload.contacts = [{ type: 'PHONE', value: phone }];
          if (updatePayload.billingPerson) {
            updatePayload.billingPerson.phone = phone;
          }
        }
        if (typeof acceptsMarketing === 'boolean') {
          updatePayload.acceptMarketing = acceptsMarketing;
        }

        const updateUrl = `https://app.ecwid.com/api/v3/${storeId}/customers/${targetId}?token=${token}`;
        const updateRes = await fetchWithRetry(updateUrl, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
            'Accept': 'application/json'
          },
          body: JSON.stringify(updatePayload)
        });

        if (!updateRes.ok) {
          const errText = await updateRes.text();
          res.statusCode = updateRes.status;
          return res.end(JSON.stringify({
            success: false,
            error: 'Failed to update customer in Ecwid',
            details: errText
          }));
        }

        const result = await updateRes.json();
        res.statusCode = 200;
        return res.end(JSON.stringify({
          success: true,
          message: 'Customer profile updated successfully in Ecwid.',
          customer: result
        }));
      } catch (err) {
        console.error('Customer update error:', err);
        res.statusCode = 500;
        return res.end(JSON.stringify({
          success: false,
          error: err.message
        }));
      }
    }

    // 6. GET /api/ecwid/payment-methods - Retrieve store-configured payment options from Ecwid
    if (cleanPath === '/api/ecwid/payment-methods' && isGetOrHead) {
      try {
        const paymentUrl = `https://app.ecwid.com/api/v3/${storeId}/profile/paymentOptions?token=${token}`;
        const paymentRes = await fetchWithRetry(paymentUrl, {
          headers: { 'Accept': 'application/json' }
        });

        if (paymentRes.ok) {
          const options = await paymentRes.json();
          res.statusCode = 200;
          return res.end(JSON.stringify({
            storeId,
            source: 'ecwid_live_api',
            paymentMethods: Array.isArray(options) ? options : []
          }));
        }

        res.statusCode = 200;
        return res.end(JSON.stringify({
          storeId,
          source: 'ecwid_configured_methods',
          paymentMethods: [
            {
              id: '1507922482-1789896468824',
              enabled: true,
              configured: true,
              checkoutTitle: 'Razorpay',
              type: 'razorpay',
              title: 'UPI / Cards / Net Banking (Razorpay)',
              description: 'Instant secure payment via UPI, Cards, and Net Banking'
            },
            {
              id: '1241677134-1787992078888',
              enabled: true,
              configured: true,
              checkoutTitle: 'Pay by cash',
              type: 'cod',
              title: 'Cash on Delivery (COD)',
              description: 'Pay in cash upon physical delivery at your doorstep'
            }
          ]
        }));
      } catch {
        res.statusCode = 200;
        return res.end(JSON.stringify({
          storeId,
          source: 'ecwid_configured_fallback',
          paymentMethods: [
            {
              id: '1507922482-1789896468824',
              enabled: true,
              configured: true,
              checkoutTitle: 'Razorpay',
              type: 'razorpay'
            },
            {
              id: '1241677134-1787992078888',
              enabled: true,
              configured: true,
              checkoutTitle: 'Pay by cash',
              type: 'cod'
            }
          ]
        }));
      }
    }

    // 7. POST /api/ecwid/order/create - Authoritative Ecwid Order Creation
    if (cleanPath === '/api/ecwid/order/create' && isPost) {
      let bodyData = {};
      if (req.body && typeof req.body === 'object') {
        bodyData = req.body;
      } else {
        bodyData = await new Promise((resolve) => {
          let buffer = '';
          req.on('data', chunk => { buffer += chunk; });
          req.on('end', () => {
            try {
              resolve(buffer ? JSON.parse(buffer) : {});
            } catch {
              resolve({});
            }
          });
          req.on('error', () => resolve({}));
        });
      }

      const { items, customer, shippingAddress, paymentMethod, totals, orderComments } = bodyData;

      if (!items || !Array.isArray(items) || items.length === 0) {
        res.statusCode = 400;
        return res.end(JSON.stringify({ error: 'Cart items are required to place an order.' }));
      }

      if (!customer || !customer.email) {
        res.statusCode = 400;
        return res.end(JSON.stringify({ error: 'Customer email is required.' }));
      }

      if (!shippingAddress || !shippingAddress.name) {
        res.statusCode = 400;
        return res.end(JSON.stringify({ error: 'Shipping address is required.' }));
      }

      const isCOD = paymentMethod === 'cod' || paymentMethod === 'Pay by cash';
      if (!isCOD) {
        res.statusCode = 400;
        return res.end(JSON.stringify({
          error: 'Online payment orders must proceed through the Ecwid native checkout session to verify payment before order creation.'
        }));
      }

      const ecwidPaymentTitle = 'Pay by cash';
      const ecwidPaymentStatus = 'AWAITING_PAYMENT';

      const ecwidItems = items.map((it) => {
        const selectedOptions = [];
        if (it.options && typeof it.options === 'object') {
          Object.entries(it.options).forEach(([name, val]) => {
            selectedOptions.push({
              name: String(name),
              value: String(val),
              type: 'CHOICE'
            });
          });
        }

        return {
          productId: Number(it.productId || it.id),
          name: it.name || '',
          price: Number(it.price || 0),
          quantity: Math.max(1, Number(it.quantity || 1)),
          sku: it.sku || '',
          selectedOptions: selectedOptions.length > 0 ? selectedOptions : undefined
        };
      });

      const orderPayload = {
        email: customer.email.trim(),
        paymentMethod: ecwidPaymentTitle,
        paymentStatus: ecwidPaymentStatus,
        fulfillmentStatus: 'AWAITING_PROCESSING',
        subtotal: Number(totals?.subtotal || 0),
        total: Number(totals?.total || totals?.subtotal || 0),
        tax: Number(totals?.tax || 0),
        items: ecwidItems,
        shippingPerson: {
          name: shippingAddress.name || '',
          companyName: shippingAddress.companyName || '',
          street: shippingAddress.street || shippingAddress.address1 || '',
          city: shippingAddress.city || '',
          countryCode: 'IN',
          countryName: 'India',
          postalCode: shippingAddress.postalCode || shippingAddress.pincode || '',
          stateOrProvinceCode: shippingAddress.state || '',
          phone: shippingAddress.phone || ''
        },
        billingPerson: {
          name: shippingAddress.name || '',
          companyName: shippingAddress.companyName || '',
          street: shippingAddress.street || shippingAddress.address1 || '',
          city: shippingAddress.city || '',
          countryCode: 'IN',
          countryName: 'India',
          postalCode: shippingAddress.postalCode || shippingAddress.pincode || '',
          stateOrProvinceCode: shippingAddress.state || '',
          phone: shippingAddress.phone || ''
        },
        shippingOption: {
          shippingMethodName: 'Standard Delivery',
          shippingRate: Number(totals?.shipping || 0)
        },
        orderComments: orderComments || undefined
      };

      const createOrderUrl = `https://app.ecwid.com/api/v3/${storeId}/orders?token=${token}`;
      const orderRes = await fetchWithRetry(createOrderUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify(orderPayload)
      });

      if (!orderRes.ok) {
        const errText = await orderRes.text();
        console.error('Failed to create Ecwid order:', errText);
        res.statusCode = orderRes.status;
        return res.end(JSON.stringify({
          error: 'Failed to create order in Ecwid',
          details: errText
        }));
      }

      let orderResult = null;
      try {
        const text = await orderRes.text();
        if (text && text.trim() && text.trim() !== 'undefined') {
          orderResult = JSON.parse(text);
        }
      } catch (e) {
        console.error('Failed to parse Ecwid orderResult JSON:', e);
      }

      if (!orderResult) {
        res.statusCode = 500;
        return res.end(JSON.stringify({ error: 'Failed to create order in Ecwid', details: 'Empty or invalid response from Ecwid orders API.' }));
      }

      res.statusCode = 200;
      return res.end(JSON.stringify({
        success: true,
        orderId: orderResult.orderId,
        id: orderResult.id,
        order: orderResult,
        paymentMethod: ecwidPaymentTitle,
        paymentStatus: ecwidPaymentStatus
      }));
    }

    return null; // Not an Ecwid API route
  } catch (err) {
    console.error('Ecwid API proxy error:', err);
    res.statusCode = 500;
    return res.end(JSON.stringify({ error: 'Internal server error while fetching Ecwid data.' }));
  }
}
