import dotenv from 'dotenv';
dotenv.config();

const DEFAULT_STORE_ID = '141633269';
// Official public token for EarthLife Co. read-only catalog access
const DEFAULT_PUBLIC_TOKEN = 'public_19bKp94DXNgXAenj9iRmy7FicBjUMQHH';

export function getEcwidConfig() {
  const storeId = process.env.ECWID_STORE_ID || process.env.VITE_ECWID_STORE_ID || DEFAULT_STORE_ID;
  const token = process.env.ECWID_SECRET_TOKEN || process.env.ECWID_PUBLIC_TOKEN || DEFAULT_PUBLIC_TOKEN;
  return { storeId, token };
}

/**
 * Normalizes an Ecwid API product object into the shape expected by EarthLife Co. UI
 */
export function normalizeProduct(raw, categories = []) {
  if (!raw) return null;

  const id = raw.id;
  const ecwidId = String(raw.id);
  const slug = raw.autogeneratedSlug || raw.customSlug || String(raw.id);
  const name = raw.name || '';
  const sku = raw.sku || '';
  const price = typeof raw.price === 'number' ? raw.price : Number(raw.price || 0);
  const compareToPrice = typeof raw.compareToPrice === 'number' && raw.compareToPrice > price 
    ? raw.compareToPrice 
    : null;
  const discountPercent = raw.compareToPriceDiscountPercent 
    || (compareToPrice ? Math.round((1 - price / compareToPrice) * 100) : null);

  // Highest resolution main image
  const image = raw.imageUrl 
    || raw.originalImageUrl 
    || raw.hdThumbnailUrl 
    || raw.thumbnailUrl 
    || raw.media?.images?.[0]?.image1500pxUrl 
    || '';

  // Clean deduplicated gallery images
  const gallery = [];
  if (image) gallery.push(image);
  
  if (Array.isArray(raw.galleryImages)) {
    raw.galleryImages.forEach(g => {
      const u = g.imageUrl || g.originalImageUrl || g.url || g.hdThumbnailUrl;
      if (u && !gallery.includes(u)) gallery.push(u);
    });
  }
  if (Array.isArray(raw.media?.images)) {
    raw.media.images.forEach(img => {
      const u = img.image1500pxUrl || img.image800pxUrl || img.imageOriginalUrl;
      if (u && !gallery.includes(u)) gallery.push(u);
    });
  }
  if (gallery.length === 0 && image) gallery.push(image);

  // Category resolution
  const categoryIds = Array.isArray(raw.categoryIds) ? raw.categoryIds : [];
  const defaultCategoryId = raw.defaultCategoryId || (categoryIds[0] ?? 0);
  
  // Resolve category name and type based on Ecwid category tree or product name
  let categoryName = 'General';
  let categoryType = 'all';
  let categoryTag = 'Natural';

  const categoryIdNum = Number(defaultCategoryId || categoryIds[0] || 0);

  if (categoryIdNum === 206710677 || name.toLowerCase().includes('neem')) {
    categoryName = 'Neem Products';
    categoryType = 'neem';
    categoryTag = 'Neem Wood';
  } else if (categoryIdNum === 206706898 || name.toLowerCase().includes('bamboo')) {
    categoryName = 'Bamboo Products';
    categoryType = 'bamboo';
    categoryTag = 'Bamboo';
  } else if (categoryIdNum === 206708145 || name.toLowerCase().includes('coconut') || name.toLowerCase().includes('coir')) {
    categoryName = 'Coconut Coir Products';
    categoryType = 'coconut';
    categoryTag = 'Coconut Coir';
  } else if (categories.length > 0) {
    const matched = categories.find(c => c.id === categoryIdNum);
    if (matched) {
      categoryName = matched.name;
      categoryTag = matched.name;
    }
  }

  return {
    id,
    ecwidId,
    slug,
    name,
    sku,
    price,
    compareToPrice,
    discountPercent,
    image,
    gallery,
    description: raw.description || '',
    inStock: Boolean(raw.inStock),
    unlimited: Boolean(raw.unlimited),
    quantity: typeof raw.quantity === 'number' ? raw.quantity : null,
    weight: typeof raw.weight === 'number' && raw.weight > 0 ? raw.weight : null,
    categoryName,
    categoryType,
    categoryTag,
    categoryId: categoryIdNum ? String(categoryIdNum) : '',
    categoryIds,
    defaultCategoryId,
    options: Array.isArray(raw.options) ? raw.options : [],
    attributes: Array.isArray(raw.attributes) ? raw.attributes : [],
    combinations: Array.isArray(raw.combinations) ? raw.combinations : [],
    url: raw.url || '',
    showOnFrontpage: typeof raw.showOnFrontpage === 'number' ? raw.showOnFrontpage : null,
    ribbon: raw.ribbon || null,
    subtitle: raw.subtitle || ''
  };
}

async function fetchWithRetry(url, options = {}, retries = 2) {
  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 8000);
      const res = await fetch(url, { ...options, signal: controller.signal });
      clearTimeout(timeoutId);
      return res;
    } catch (err) {
      if (attempt === retries) throw err;
      await new Promise(r => setTimeout(r, 300 * (attempt + 1)));
    }
  }
}

const ECWID_CATEGORY_MAP = {
  neem: '206710677',
  'neem-products': '206710677',
  bamboo: '206706898',
  'bamboo-products': '206706898',
  coconut: '206708145',
  'coconut-coir': '206708145',
  'cotton-coir': '206708145',
  'coir': '206708145',
  'cotton': '206708145',
  'coconut-coir-products': '206708145',
};

function resolveCategoryId(cat) {
  if (!cat || cat === '0' || cat === 'all') return null;
  const normalized = String(cat).trim().toLowerCase();
  if (ECWID_CATEGORY_MAP[normalized]) return ECWID_CATEGORY_MAP[normalized];
  if (/^\d+$/.test(normalized)) return normalized;
  return null;
}

/**
 * Handles incoming Ecwid API proxy requests
 */
export async function handleEcwidApi(req, res) {
  const urlObj = new URL(req.url, 'http://localhost');
  const pathname = urlObj.pathname;
  const cleanPath = pathname.replace(/\/+$/, '') || '/';
  const { storeId, token } = getEcwidConfig();

  // Set permissive CORS and JSON headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, HEAD, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Accept, Authorization');
  res.setHeader('Content-Type', 'application/json');

  if (req.method === 'OPTIONS') {
    res.statusCode = 204;
    return res.end();
  }

  const isGetOrHead = req.method === 'GET' || req.method === 'HEAD';

  try {
    // 1. GET /api/ecwid/products
    if (cleanPath === '/api/ecwid/products' && isGetOrHead) {
      const keyword = urlObj.searchParams.get('keyword');
      const category = urlObj.searchParams.get('category');
      const limit = urlObj.searchParams.get('limit') || '100';
      const offset = urlObj.searchParams.get('offset') || '0';

      const ecwidUrl = new URL(`https://app.ecwid.com/api/v3/${storeId}/products`);
      ecwidUrl.searchParams.set('token', token);
      ecwidUrl.searchParams.set('limit', limit);
      ecwidUrl.searchParams.set('offset', offset);
      if (keyword) ecwidUrl.searchParams.set('keyword', keyword);
      const resolvedCategory = resolveCategoryId(category);
      if (resolvedCategory) {
        ecwidUrl.searchParams.set('category', resolvedCategory);
      }

      const response = await fetchWithRetry(ecwidUrl.toString(), {
        headers: { 'Accept': 'application/json' }
      });

      if (!response.ok) {
        const errorText = await response.text();
        res.statusCode = response.status;
        return res.end(JSON.stringify({ 
          error: `Ecwid API error: ${response.statusText}`, 
          details: errorText 
        }));
      }

      const data = await response.json();
      const normalizedItems = (data.items || []).map(p => normalizeProduct(p));

      res.statusCode = 200;
      return res.end(JSON.stringify({
        storeId,
        source: 'ecwid_live_api',
        total: data.total,
        count: data.count,
        offset: data.offset,
        limit: data.limit,
        items: normalizedItems,
        rawItems: data.items
      }));
    }

    // 2. GET /api/ecwid/products/:id
    if (cleanPath.startsWith('/api/ecwid/products/') && isGetOrHead) {
      const idOrSlug = decodeURIComponent(cleanPath.replace('/api/ecwid/products/', '')).trim();

      if (!idOrSlug) {
        res.statusCode = 400;
        return res.end(JSON.stringify({ error: 'Product ID or slug is required.' }));
      }

      const isNumeric = /^\d+$/.test(idOrSlug);

      if (isNumeric) {
        // Direct fetch by numeric ID
        const singleUrl = `https://app.ecwid.com/api/v3/${storeId}/products/${idOrSlug}?token=${token}`;
        const singleRes = await fetchWithRetry(singleUrl, {
          headers: { 'Accept': 'application/json' }
        });

        if (singleRes.ok) {
          const raw = await singleRes.json();
          res.statusCode = 200;
          return res.end(JSON.stringify({
            storeId,
            source: 'ecwid_live_api',
            product: normalizeProduct(raw),
            raw
          }));
        }
      }

      // If not numeric or direct fetch failed, search products to match by slug or SKU
      const searchUrl = `https://app.ecwid.com/api/v3/${storeId}/products?token=${token}&limit=100`;
      const searchRes = await fetchWithRetry(searchUrl, {
        headers: { 'Accept': 'application/json' }
      });

      if (!searchRes.ok) {
        res.statusCode = 404;
        return res.end(JSON.stringify({ error: 'Product not found.' }));
      }

      const listData = await searchRes.json();
      const match = (listData.items || []).find(p => 
        String(p.id) === idOrSlug ||
        p.autogeneratedSlug === idOrSlug ||
        p.customSlug === idOrSlug ||
        (p.sku && p.sku.toLowerCase() === idOrSlug.toLowerCase()) ||
        idOrSlug.includes(p.autogeneratedSlug) ||
        (p.autogeneratedSlug && p.autogeneratedSlug.includes(idOrSlug))
      );

      if (!match) {
        res.statusCode = 404;
        return res.end(JSON.stringify({ error: 'Product not found.' }));
      }

      // Fetch full individual product for complete gallery and options
      const fullRes = await fetchWithRetry(`https://app.ecwid.com/api/v3/${storeId}/products/${match.id}?token=${token}`, {
        headers: { 'Accept': 'application/json' }
      });

      const raw = fullRes.ok ? await fullRes.json() : match;
      res.statusCode = 200;
      return res.end(JSON.stringify({
        storeId,
        source: 'ecwid_live_api',
        product: normalizeProduct(raw),
        raw
      }));
    }

    // 3. GET /api/ecwid/categories
    if (cleanPath === '/api/ecwid/categories' && isGetOrHead) {
      const catUrl = `https://app.ecwid.com/api/v3/${storeId}/categories?token=${token}`;
      const catRes = await fetchWithRetry(catUrl, {
        headers: { 'Accept': 'application/json' }
      });

      if (!catRes.ok) {
        const errText = await catRes.text();
        res.statusCode = catRes.status;
        return res.end(JSON.stringify({ error: 'Failed to fetch categories', details: errText }));
      }

      const data = await catRes.json();
      res.statusCode = 200;
      return res.end(JSON.stringify({
        storeId,
        source: 'ecwid_live_api',
        total: data.total,
        items: data.items || []
      }));
    }

    return null; // Not an Ecwid API route
  } catch (err) {
    console.error('Ecwid API proxy error:', err);
    res.statusCode = 500;
    return res.end(JSON.stringify({ error: 'Internal server error while fetching Ecwid data.' }));
  }
}
