/**
 * EarthLife Co. - Ecwid Live Storefront Client
 * Primary: Communicates with backend proxy (/api/ecwid/*)
 * Fallback: Direct Ecwid REST API using public storefront token (CORS-enabled read-only token)
 */

const ECWID_STORE_ID = import.meta.env.VITE_ECWID_STORE_ID || '141633269';
// Official public read-only storefront token for store 141633269
const ECWID_PUBLIC_TOKEN = 'public_19bKp94DXNgXAenj9iRmy7FicBjUMQHH';

function getApiBaseUrl() {
  const envUrl = (import.meta.env.VITE_API_BASE_URL || '').trim();
  if (!envUrl) return '';
  // Avoid fetching localhost when previewing on Cloud Run or external host
  if (typeof window !== 'undefined' && envUrl.includes('localhost') && !window.location.hostname.includes('localhost')) {
    return '';
  }
  return envUrl.endsWith('/') ? envUrl.slice(0, -1) : envUrl;
}

/**
 * Normalizes a raw Ecwid product object
 */
export function normalizeEcwidProduct(raw, categories = []) {
  if (!raw) return null;

  const id = raw.id;
  const ecwidId = String(raw.id);
  const slug = raw.autogeneratedSlug || raw.customSlug || String(raw.id);
  const name = raw.name || '';
  const sku = raw.sku || '';
  const price = typeof raw.price === 'number' ? raw.price : Number(raw.price || 0);
  const compareToPrice = typeof raw.compareToPrice === 'number' && raw.compareToPrice > price 
    ? raw.compareToPrice 
    : null;
  const discountPercent = raw.compareToPriceDiscountPercent 
    || (compareToPrice ? Math.round((1 - price / compareToPrice) * 100) : null);

  const image = raw.imageUrl 
    || raw.originalImageUrl 
    || raw.hdThumbnailUrl 
    || raw.thumbnailUrl 
    || raw.media?.images?.[0]?.image1500pxUrl 
    || '';

  const gallery = [];
  if (image) gallery.push(image);
  
  if (Array.isArray(raw.galleryImages)) {
    raw.galleryImages.forEach(g => {
      const u = g.imageUrl || g.originalImageUrl || g.url || g.hdThumbnailUrl;
      if (u && !gallery.includes(u)) gallery.push(u);
    });
  }
  if (Array.isArray(raw.media?.images)) {
    raw.media.images.forEach(img => {
      const u = img.image1500pxUrl || img.image800pxUrl || img.imageOriginalUrl;
      if (u && !gallery.includes(u)) gallery.push(u);
    });
  }
  if (gallery.length === 0 && image) gallery.push(image);

  const categoryIds = Array.isArray(raw.categoryIds) ? raw.categoryIds : [];
  const defaultCategoryId = raw.defaultCategoryId || (categoryIds[0] ?? 0);
  
  let categoryName = 'General';
  let categoryType = 'all';
  let categoryTag = 'Natural';

  const categoryIdNum = Number(defaultCategoryId || categoryIds[0] || 0);

  if (categoryIdNum === 206710677 || name.toLowerCase().includes('neem')) {
    categoryName = 'Neem Products';
    categoryType = 'neem';
    categoryTag = 'Neem Wood';
  } else if (categoryIdNum === 206706898 || name.toLowerCase().includes('bamboo')) {
    categoryName = 'Bamboo Products';
    categoryType = 'bamboo';
    categoryTag = 'Bamboo';
  } else if (categoryIdNum === 206708145 || name.toLowerCase().includes('coconut') || name.toLowerCase().includes('coir')) {
    categoryName = 'Coconut Coir Products';
    categoryType = 'coconut';
    categoryTag = 'Coconut Coir';
  } else if (categories.length > 0) {
    const matched = categories.find(c => c.id === categoryIdNum);
    if (matched) {
      categoryName = matched.name;
      categoryTag = matched.name;
    }
  }

  return {
    id,
    ecwidId,
    slug,
    name,
    sku,
    price,
    compareToPrice,
    discountPercent,
    image,
    gallery,
    description: raw.description || '',
    inStock: Boolean(raw.inStock),
    unlimited: Boolean(raw.unlimited),
    quantity: typeof raw.quantity === 'number' ? raw.quantity : null,
    weight: typeof raw.weight === 'number' && raw.weight > 0 ? raw.weight : null,
    categoryName,
    categoryType,
    categoryTag,
    categoryId: categoryIdNum ? String(categoryIdNum) : '',
    categoryIds,
    defaultCategoryId,
    options: Array.isArray(raw.options) ? raw.options : [],
    attributes: Array.isArray(raw.attributes) ? raw.attributes : [],
    combinations: Array.isArray(raw.combinations) ? raw.combinations : [],
    url: raw.url || '',
    showOnFrontpage: typeof raw.showOnFrontpage === 'number' ? raw.showOnFrontpage : null,
    ribbon: raw.ribbon || null,
    subtitle: raw.subtitle || ''
  };
}

const CACHE_KEY_PRODUCTS = 'earthlife_ecwid_products_cache';
const CACHE_KEY_CATEGORIES = 'earthlife_ecwid_categories_cache';

function getSessionCache(key) {
  try {
    if (typeof window !== 'undefined' && window.sessionStorage) {
      const item = window.sessionStorage.getItem(key);
      return item ? JSON.parse(item) : null;
    }
  } catch {
    return null;
  }
  return null;
}

function setSessionCache(key, data) {
  try {
    if (typeof window !== 'undefined' && window.sessionStorage && data) {
      window.sessionStorage.setItem(key, JSON.stringify(data));
    }
  } catch {
    // Ignore storage quota errors
  }
}

export const ECWID_CATEGORY_IDS = {
  neem: '206710677',
  'neem-products': '206710677',
  bamboo: '206706898',
  'bamboo-products': '206706898',
  coconut: '206708145',
  'coconut-coir': '206708145',
  'cotton-coir': '206708145',
  'coir': '206708145',
  'cotton': '206708145',
  'coconut-coir-products': '206708145'
};

export function resolveEcwidCategoryId(category) {
  if (!category || category === 'all' || category === '0') return null;
  const str = String(category).trim().toLowerCase();
  if (ECWID_CATEGORY_IDS[str]) return ECWID_CATEGORY_IDS[str];
  if (/^\d+$/.test(str)) return str;
  return null;
}

/**
 * Fetch products from live Ecwid store via API proxy with direct public API fallback
 * @param {Object} [options]
 * @param {string} [options.category]
 * @param {string} [options.keyword]
 * @param {number} [options.limit]
 * @param {number} [options.offset]
 */
export async function fetchEcwidProducts(options = {}) {
  const baseUrl = getApiBaseUrl();
  const endpoint = `${baseUrl}/api/ecwid/products`;

  const params = new URLSearchParams();
  const resolvedCat = resolveEcwidCategoryId(options.category);
  if (resolvedCat) {
    params.set('category', resolvedCat);
  }
  if (options.keyword) {
    params.set('keyword', options.keyword);
  }
  if (options.limit !== undefined && options.limit !== null) {
    params.set('limit', String(options.limit));
  }
  if (options.offset !== undefined && options.offset !== null) {
    params.set('offset', String(options.offset));
  }
  const queryString = params.toString() ? `?${params.toString()}` : '';

  // 1. Try local/server API proxy first with retry
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const response = await fetch(`${endpoint}${queryString}`);

      if (response.ok) {
        const contentType = response.headers.get("content-type");
        if (contentType && contentType.indexOf("application/json") !== -1) {
          const data = await response.json();
          if (Array.isArray(data.items)) {
            if (!options.category && !options.keyword && !options.offset) {
              setSessionCache(CACHE_KEY_PRODUCTS, data);
            }
            return data;
          }
        } else {
          const text = await response.text();
          console.error("Proxy fetch returned non-JSON:", text.substring(0, 100));
          throw new Error("API proxy returned invalid JSON format.");
        }
      }
    } catch (proxyError) {
      if (attempt === 0) {
        await new Promise(r => setTimeout(r, 350));
      } else {
        console.warn('Proxy fetch failed, attempting direct public Ecwid API fallback:', proxyError.message);
      }
    }
  }

  // 2. Direct fallback to official Ecwid Public Storefront API (simple CORS request without custom headers)
  try {
    const directUrl = new URL(`https://app.ecwid.com/api/v3/${ECWID_STORE_ID}/products`);
    directUrl.searchParams.set('token', ECWID_PUBLIC_TOKEN);
    directUrl.searchParams.set('limit', String(options.limit || 100));
    directUrl.searchParams.set('offset', String(options.offset || 0));
    if (options.keyword) directUrl.searchParams.set('keyword', options.keyword);
    if (resolvedCat) {
      directUrl.searchParams.set('category', resolvedCat);
    }

    const directRes = await fetch(directUrl.toString(), { mode: 'cors' });

    if (!directRes.ok) {
      throw new Error(`Ecwid API error (${directRes.status})`);
    }

    const rawData = await directRes.json();
    const rawItems = Array.isArray(rawData.items) ? rawData.items : [];
    const normalizedItems = rawItems.map(item => normalizeEcwidProduct(item));

    const result = {
      storeId: ECWID_STORE_ID,
      source: 'ecwid_direct_fallback',
      total: rawData.total ?? normalizedItems.length,
      count: normalizedItems.length,
      offset: rawData.offset ?? 0,
      limit: rawData.limit ?? (options.limit || 100),
      items: normalizedItems
    };

    if (!options.category && !options.keyword && !options.offset) {
      setSessionCache(CACHE_KEY_PRODUCTS, result);
    }
    return result;
  } catch (directError) {
    console.warn('Direct Ecwid API fetch error:', directError.message);

    // 3. Last resilient resort: check session cache
    const cached = getSessionCache(CACHE_KEY_PRODUCTS);
    if (cached && Array.isArray(cached.items) && cached.items.length > 0) {
      console.info('Serving cached Ecwid catalog due to temporary network error.');
      return cached;
    }

    throw new Error('Unable to load live Ecwid catalog. Please check your network connection.');
  }
}

/**
 * Fetch a single product by its Ecwid ID or slug with direct public API fallback
 * @param {string|number} idOrSlug
 */
export async function fetchEcwidProductById(idOrSlug) {
  if (!idOrSlug) {
    throw new Error('Product ID or slug is required');
  }

  const baseUrl = getApiBaseUrl();
  const encoded = encodeURIComponent(String(idOrSlug));
  const endpoint = `${baseUrl}/api/ecwid/products/${encoded}`;

  // 1. Try local/server API proxy first with retry
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const response = await fetch(endpoint);

      if (response.ok) {
        const data = await response.json();
        if (data.product) {
          return data.product;
        }
      }
    } catch (proxyError) {
      if (attempt === 0) {
        await new Promise(r => setTimeout(r, 350));
      } else {
        console.warn('Proxy product fetch failed, attempting direct public Ecwid API fallback:', proxyError.message);
      }
    }
  }

  // 2. Direct fallback to Ecwid Public API (no custom headers to avoid CORS preflight rejection)
  try {
    const isNumeric = /^\d+$/.test(String(idOrSlug).trim());

    if (isNumeric) {
      const directUrl = `https://app.ecwid.com/api/v3/${ECWID_STORE_ID}/products/${idOrSlug}?token=${ECWID_PUBLIC_TOKEN}`;
      const res = await fetch(directUrl, { mode: 'cors' });
      if (res.ok) {
        const raw = await res.json();
        return normalizeEcwidProduct(raw);
      }
    }

    // If slug or numeric lookup directly failed, fetch catalog list and search
    const listUrl = `https://app.ecwid.com/api/v3/${ECWID_STORE_ID}/products?token=${ECWID_PUBLIC_TOKEN}&limit=100`;
    const listRes = await fetch(listUrl, { mode: 'cors' });
    if (listRes.ok) {
      const listData = await listRes.json();
      const rawList = Array.isArray(listData.items) ? listData.items : [];
      const match = rawList.find(p => 
        String(p.id) === String(idOrSlug) ||
        p.autogeneratedSlug === idOrSlug ||
        p.customSlug === idOrSlug ||
        (p.sku && p.sku.toLowerCase() === String(idOrSlug).toLowerCase())
      );
      if (match) {
        return normalizeEcwidProduct(match);
      }
    }

    // Check cached catalog
    const cached = getSessionCache(CACHE_KEY_PRODUCTS);
    if (cached && Array.isArray(cached.items)) {
      const matchCached = cached.items.find(p =>
        String(p.id) === String(idOrSlug) ||
        p.slug === idOrSlug ||
        (p.sku && p.sku.toLowerCase() === String(idOrSlug).toLowerCase())
      );
      if (matchCached) return matchCached;
    }

    throw new Error(`Product not found in Ecwid catalog`);
  } catch (directError) {
    console.warn('Direct Ecwid product lookup error:', directError.message);

    const cached = getSessionCache(CACHE_KEY_PRODUCTS);
    if (cached && Array.isArray(cached.items)) {
      const matchCached = cached.items.find(p =>
        String(p.id) === String(idOrSlug) ||
        p.slug === idOrSlug ||
        (p.sku && p.sku.toLowerCase() === String(idOrSlug).toLowerCase())
      );
      if (matchCached) return matchCached;
    }

    throw new Error(`Product not found (${idOrSlug})`);
  }
}

/**
 * Fetch categories from live Ecwid store with direct public API fallback
 */
export async function fetchEcwidCategories() {
  const baseUrl = getApiBaseUrl();
  const endpoint = `${baseUrl}/api/ecwid/categories`;

  // 1. Try local/server API proxy first with retry
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const response = await fetch(endpoint);

      if (response.ok) {
        const contentType = response.headers.get("content-type");
        if (contentType && contentType.indexOf("application/json") !== -1) {
          const data = await response.json();
          if (Array.isArray(data.items)) {
            setSessionCache(CACHE_KEY_CATEGORIES, data);
            return data;
          }
        } else {
          const text = await response.text();
          console.error("Proxy categories fetch returned non-JSON:", text.substring(0, 100));
          throw new Error("API proxy categories returned invalid JSON format.");
        }
      }
    } catch (proxyError) {
      if (attempt === 0) {
        await new Promise(r => setTimeout(r, 350));
      } else {
        console.warn('Proxy categories fetch failed, attempting direct public Ecwid API fallback:', proxyError.message);
      }
    }
  }

  // 2. Direct fallback (mode: 'cors', no custom headers)
  try {
    const directUrl = `https://app.ecwid.com/api/v3/${ECWID_STORE_ID}/categories?token=${ECWID_PUBLIC_TOKEN}`;
    const res = await fetch(directUrl, { mode: 'cors' });
    if (res.ok) {
      const data = await res.json();
      setSessionCache(CACHE_KEY_CATEGORIES, data);
      return data;
    }
    throw new Error(`Failed to fetch categories (${res.status})`);
  } catch (err) {
    console.warn('Categories lookup error:', err.message);

    const cached = getSessionCache(CACHE_KEY_CATEGORIES);
    if (cached && Array.isArray(cached.items) && cached.items.length > 0) {
      console.info('Serving cached Ecwid categories.');
      return cached;
    }

    throw err;
  }
}
